# Contains all tumor samples from patient RG13
samples:
  RG10N: /data/koplev01/OVCT/EvisAlign2/RG10N.bam
  RG10T17: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG10T17.bam
  RG10T18: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG10T18.bam
  RG10T19: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG10T19.bam
  RG10T5: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG10T5.bam
  RG10T7: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG10T7.bam
  RG10T8: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG10T8.bam
  RG13N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG13N.bam
  RG13T10: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG13T10.bam
  RG13T11: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG13T11.bam
  RG13T122: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG13T122.bam
  RG13T13: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG13T13.bam
  RG13T14: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG13T14.bam
  RG16N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG16N.bam
  RG16T1: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG16T1.bam
  RG16T3: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG16T3.bam
  RG16T5: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG16T5.bam
  RG16T9: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG16T9.bam
  RG17N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17N.bam
  RG17T13: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17T13.bam
  RG17T14: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17T14.bam
  RG17T19: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17T19.bam
  RG17T6: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17T6.bam
  RG17T7: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17T7.bam
  RG17T9: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG17T9.bam
  RG19-N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG19-N.bam
  RG19-T10: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG19-T10.bam
  RG19-T11: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG19-T11.bam
  RG19-T7: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG19-T7.bam
  RG19-T8: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG19-T8.bam
  RG19-T9: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG19-T9.bam
  RG1N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG1N.bam
  RG1T3: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG1T3.bam
  RG1T5: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG1T5.bam
  RG1T6: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG1T6.bam
  RG1T7: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG1T7.bam
  RG20-N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG20-N.bam
  RG20-T10: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG20-T10.bam
  RG20-T12: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG20-T12.bam
  RG20-T14: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG20-T14.bam
  RG20-T8: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG20-T8.bam
  RG4N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG4N.bam
  RG4T1: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG4T1.bam
  RG4T2: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG4T2.bam
  RG4T3: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG4T3.bam
  RG4T4: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG4T4.bam
  RG4T5: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG4T5.bam
  RG5N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5N.bam
  RG5T12: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T12.bam
  RG5T13: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T13.bam
  RG5T14Rep: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T14Rep.bam
  RG5T15: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T15.bam
  RG5T16: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T16.bam
  RG5T17: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T17.bam
  RG5T22: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG5T22.bam
  RG6N: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG6N.bam
  RG6T12: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG6T12.bam
  RG6T13: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG6T13.bam
  RG6T16: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG6T16.bam
  RG6T3: /data/general/ajs_share/ovct_data/WES/EvisRedHardDrive/RG6T3.bam

pairings:
  # RG10N
  RG10T17: RG10N
  RG10T18: RG10N
  RG10T19: RG10N
  RG10T5: RG10N
  RG10T7: RG10N
  RG10T8: RG10N
  # RG13N
  RG13T10: RG13N
  RG13T11: RG13N
  RG13T122: RG13N
  RG13T13: RG13N
  RG13T14: RG13N
  # RG16N
  RG16T1: RG16N
  RG16T3: RG16N
  RG16T5: RG16N
  RG16T9: RG16N
  # RG17N
  RG17T13: RG17N
  RG17T14: RG17N
  RG17T19: RG17N
  RG17T6: RG17N
  RG17T7: RG17N
  RG17T9: RG17N
  # RG19-N
  RG19-T10: RG19-N
  RG19-T11: RG19-N
  RG19-T7: RG19-N
  RG19-T8: RG19-N
  RG19-T9: RG19-N
  # RG1N
  RG1T3: RG1N
  RG1T5: RG1N
  RG1T6: RG1N
  RG1T7: RG1N
  # RG20-N
  RG20-T10: RG20-N
  RG20-T12: RG20-N
  RG20-T14: RG20-N
  RG20-T8: RG20-N
  # RG4N
  RG4T1: RG4N
  RG4T2: RG4N
  RG4T3: RG4N
  RG4T4: RG4N
  RG4T5: RG4N
  # RG5N
  RG5T12: RG5N
  RG5T13: RG5N
  RG5T14Rep: RG5N
  RG5T15: RG5N
  RG5T16: RG5N
  RG5T17: RG5N
  RG5T22: RG5N
  # RG6N
  RG6T12: RG6N
  RG6T13: RG6N
  RG6T16: RG6N
  RG6T3: RG6N
